name: Jupyter notebook to HTML and PDF format uploaded as artifact

on:
  push:
    branches: [ master ]

jobs:
  nbconvert:
    runs-on: ubuntu-latest
    env:
      ipynb_file_path: research_paper_analysis.ipynb
    steps:
      - uses: actions/checkout@v2

      - name: Convert notebook to other format 
        run: |
          sudo apt-get install pandoc texlive-xetex texlive-fonts-recommended texlive-plain-generic
          pip install notebook
          pip install nbconvert
          jupyter nbconvert --to pdf $ipynb_file_path
          jupyter nbconvert --to html $ipynb_file_path
          
      - uses: actions/upload-artifact@v2
        with:
          name: research_paper_analysis (PDF)
          path: research_paper_analysis.pdf
          
      - uses: actions/upload-artifact@v2
        with:
          name: research_paper_analysis (HTML)
          path: research_paper_analysis.html
