name: Notebook to HTML

on:
  push:
    branches: [ master ]

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Convert notebook to HTML 
        run: |
          sudo apt-get install pandoc
          sudo apt-get install texlive-xetex texlive-fonts-recommended texlive-plain-generic
          pip install notebook
          pip install nbconvert
          jupyter nbconvert --to pdf research_paper_analysis.ipynb
          
      - uses: actions/upload-artifact@v2
        with:
          name: research_paper_analysis
          path: research_paper_analysis.html
